# Generated by Django 3.2.25 on 2024-12-16 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='tag',
            field=models.CharField(max_length=255),
        ),
    ]
